title: This is me!
author: Jhanvi Pai
email: pai.jhanvipai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am an AP Schlar with Distinction. I also received the EB Women's Club Aware before graduating from East Brunswick High School. I will be attending New 
  Jersey Insitute of Technology's Honors College as a Human Computer Itneraction. During my free time, I like to listen to music, 
  cook, hangout with friends and read. 

theme: minima
# social links
instagram_username: jpai_15
github_username:  pai.jhanvipai@gmail.com # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
